### ISSUE TITLE
Default on CentOS 7 this installs 1.5 

### ISSUE THREAD

**Issue by onknows** [robertdebock/ansible-role-haproxy#4]
I think default on CentOS 7 this installs version 1.5 which is no longer supported.  Which has reached EOF. https://www.haproxy.org/

There is a epel version haproxy18 which has 1.8 which looks better but I don't know what that is. For example it doesn't include a service, there is no config directory.

I don't have any experience with HAProxy. Should we use a paid version? Or Install this from source? Some people are installing from source it seems for example https://laptrinhx.com/how-to-install-haproxy-1-9-on-centos-7-1410983782/

**Comment by robertdebock** [comment]
CentOS 7 comes with haproxy 1.5, that's unrelated to this role. CentOS 7 will be [unsupported](https://wiki.centos.org/About/Product) soon. I suggest to update the operating system.
