### ISSUE TITLE
Add more flexibility in `servers` variable setup

### ISSUE THREAD

**Issue by vmaillot** [robertdebock/ansible-role-haproxy#5]
## Proposed feature

At the moment the `servers` are fetch from the `group[all]` which obliges us to have them in the inventory. And it will trigger an access to the servers (we do not want that at this stage).

## Rationale

This feature is required because we will use this role for a customer deployment.

## Additional context

Just ping me if anything is not clear. Thanks a lot for taking care of this!

**Comment by robertdebock** [comment]
Fixes with the latest release, please update. (`ansible-galaxy install robertdebock.haproxy -f`)
