### ISSUE TITLE
Add configurable `mode` for backends/frontends

### ISSUE THREAD

**Issue by vmaillot** [robertdebock/ansible-role-haproxy#6]
## Proposed feature

At the moment there is no way to configure the mode of the frontends/backens (http, tcp...). It would be nice to have this feature available!

## Rationale

This feature is required because we will use this role for a customer deployment.

## Additional context

Just ping me if anything is not clear. Thanks a lot for taking care of this!

**Comment by robertdebock** [comment]
Fixes with the latest release, please update. (`ansible-galaxy install robertdebock.haproxy -f`)
